using System;
using System.Collections.Generic;
using InventoryTools.Logic.Settings.Abstract;

namespace InventoryTools.Services;

/// <summary>
/// Traditional Chinese display text for the API13 build. This deliberately
/// changes only labels/help text at runtime; configuration keys and values stay intact.
/// </summary>
public static class TwSettingsLocalization
{
    private static readonly Dictionary<string, string> Text = new(StringComparer.Ordinal)
    {
        // Setting names
        ["Active Craft List"] = "目前製作清單",
        ["Add Title Menu Button?"] = "加入標題畫面按鈕？",
        ["Show Cross-Character Inventories in Lists?"] = "在清單顯示其他角色庫存？",
        ["Auto save inventories/configuration?"] = "自動儲存庫存與設定？",
        ["Auto save every"] = "自動儲存間隔",
        ["Automatically download prices?"] = "自動下載市場價格？",
        ["Background List Highlighting"] = "背景清單標示",
        ["Color name in retainer list?"] = "在雇員清單標示名稱？",
        ["Context Menu - Add to Active Craft List"] = "右鍵選單－加入目前製作清單",
        ["Context Menu - Add to Craft List"] = "右鍵選單－加入製作清單",
        ["Context Menu - Add to Curated List"] = "右鍵選單－加入自訂清單",
        ["Context Menu - Add/Remove to Favourites"] = "右鍵選單－加入／移除最愛",
        ["Context Menu - Search Scope"] = "右鍵選單－搜尋範圍",
        ["Context Menu - Search"] = "右鍵選單－搜尋物品",
        ["Context Menu - More Information"] = "右鍵選單－更多資訊",
        ["Context Menu - Open Crafting Log"] = "右鍵選單－開啟製作筆記",
        ["Context Menu - Open Fishing Log"] = "右鍵選單－開啟釣魚手冊",
        ["Context Menu - Open Gathering Log"] = "右鍵選單－開啟採集筆記",
        ["Craft Window Layout"] = "製作視窗版面",
        ["Craft Window View"] = "製作視窗檢視方式",
        ["Enable Tetris?"] = "啟用俄羅斯方塊？",
        ["Items Window Layout"] = "物品視窗版面",
        ["Highlight Colour"] = "標示顏色",
        ["Destination Highlight Colour"] = "目的地標示顏色",
        ["Highlight Destination?"] = "標示目的地物品？",
        ["Highlight Empty Destination?"] = "標示目的地空格？",
        ["Highlight When?"] = "何時啟用標示？",
        ["Enable History Tracking?"] = "啟用歷史追蹤？",
        ["History Track Events"] = "要追蹤的歷史事件",
        ["Open Item Log Hotkey"] = "開啟物品相關筆記快捷鍵",
        ["Toggle Airships Window"] = "切換飛空艇視窗",
        ["Toggle Configuration Window"] = "切換設定視窗",
        ["Toggle Craft Window"] = "切換製作視窗",
        ["Toggle Duties Window"] = "切換任務視窗",
        ["Toggle Lists Window"] = "切換物品清單視窗",
        ["Toggle Mob Window"] = "切換怪物視窗",
        ["More Information Hotkey"] = "更多資訊快捷鍵",
        ["Open Crafting Log Hotkey"] = "開啟製作筆記快捷鍵",
        ["Open Fishing Log Hotkey"] = "開啟釣魚手冊快捷鍵",
        ["Open Gathering Log Hotkey"] = "開啟採集筆記快捷鍵",
        ["Toggle Retainer Ventures Window"] = "切換雇員探險視窗",
        ["Toggle Submarines Window"] = "切換潛水艇視窗",
        ["Invert Destination Highlighting?"] = "反轉目的地標示？",
        ["Invert Highlighting?"] = "反轉物品標示？",
        ["Invert Tab Highlighting?"] = "反轉分頁標示？",
        ["Price Worlds"] = "價格查詢世界",
        ["Marketboard Sale History Days"] = "市場成交紀錄天數",
        ["Price Active World?"] = "查詢目前世界價格？",
        ["Price Home World?"] = "查詢所屬世界價格？",
        ["Keep market prices for X hours"] = "市場價格保留時數",
        ["Retainer List Colour"] = "雇員清單標示顏色",
        ["Keep Background List Highlighting?"] = "保留背景清單標示？",
        ["Show 'All Lists' Tab?"] = "顯示「所有清單」分頁？",
        ["Show item number in retainer list?"] = "在雇員清單顯示物品數量？",
        ["Enable Tooltip Tweaks?"] = "啟用物品提示增強？",
        ["Source Acquisition Icon Grouping"] = "取得來源圖示分組",
        ["Switch craft lists automatically?"] = "自動切換製作清單？",
        ["Switch lists automatically?"] = "自動切換物品清單？",
        ["Tab Highlight Colour"] = "分頁標示顏色",
        ["Add Item Locations (Max Results)"] = "加入物品位置（最多筆數）",
        ["Add Item Locations (Affix with Character Name)"] = "加入物品位置（附上角色名稱）",
        ["Add Item Locations (Order)"] = "加入物品位置（排序）",
        ["Add Market Average NQ/HQ Price"] = "加入市場平均 NQ／HQ 價格",
        ["Tooltip Category Blacklist"] = "提示分類黑名單",
        ["Tooltip Category Whitelist"] = "提示分類白名單",
        ["Text Colour"] = "文字顏色",
        ["Limit to items on the current character?"] = "僅顯示目前角色的物品？",
        ["Add Item Locations"] = "加入物品持有位置",
        ["Add Plugin Name"] = "加入插件名稱",
        ["Add Amount to Retrieve"] = "加入需取出數量",
        ["Add Item Unlock Status (Characters)"] = "加入解鎖狀態（角色）",
        ["Add Item Unlock Status"] = "加入物品解鎖狀態",
        ["Footer New Lines"] = "提示底部空行數",
        ["Header New Lines"] = "提示頂部空行數",
        ["Add Item Locations (Display Mode)"] = "加入物品位置（顯示方式）",
        ["Add Item Locations (Search Locations)"] = "加入物品位置（搜尋範圍）",
        ["Add Market Minimum NQ/HQ Price?"] = "加入市場最低 NQ／HQ 價格？",
        ["Source Information Configuration"] = "取得來源資訊設定",
        ["Use Information Configuration"] = "用途資訊設定",
        ["Track Mob Spawns"] = "記錄怪物出現位置",
        ["Use Acquisition Icon Grouping"] = "用途圖示分組",
        ["Window List Highlighting"] = "視窗開啟時標示的清單",
        ["Login Delay"] = "登入後掃描延遲",
        ["Persist State Time (seconds)"] = "狀態保留時間（秒）",
        ["Hide during duties?"] = "任務中隱藏？",
        ["Max items when expanded"] = "展開時最多顯示項目",
        ["Remember State"] = "記住視窗狀態",
        ["Window State"] = "視窗狀態",
        ["Shop Highlighting - Disable Items"] = "商店標示－停用未標示物品",
        ["Add Ingredient Patch"] = "加入素材最後使用版本",
        ["Add Item Unlock Status (Display Mode)"] = "加入物品解鎖狀態（顯示方式）",
        ["Add Item Unlock Status (Hide Unlocked Characters)"] = "加入物品解鎖狀態（隱藏已解鎖角色）",
        ["Source Information Enabled"] = "啟用取得來源資訊",
        ["Source Information Modifier Key"] = "取得來源資訊輔助鍵",
        ["Use Information Enabled"] = "啟用用途資訊",
        ["Use Information Modifier Key"] = "用途資訊輔助鍵",
        ["Use Old Craft Tracker?"] = "使用舊版製作追蹤？",
        ["Item Tooltip Mode"] = "物品提示觸發方式",

        // Configuration wizard features
        ["Basic"] = "基本設定",
        ["Context Menus"] = "右鍵選單",
        ["Sample Item Lists"] = "範例物品清單",
        ["Hotkeys"] = "快捷鍵",
        ["Tooltips"] = "物品提示",
        ["Layout"] = "版面配置",
        ["Marketboard"] = "市場布告板",
        ["Configure the basic settings of Allagan Tools"] = "設定 Allagan Tools 的基本功能。",
        ["Adds new items to the right click/context menu for items in the game. "] = "在遊戲物品的右鍵選單加入 Allagan Tools 功能。",
        ["Select which sample item lists you'd like to install by default. These are good examples of the types of lists that are possible within Allagan Tools."] = "選擇要預先安裝的範例物品清單；可用來了解 Allagan Tools 能建立哪些類型的清單。",
        ["Set hotkeys for opening the various Allagan Tools windows. A hotkey to open the 'More Information' window for items is also available."] = "設定開啟各個 Allagan Tools 視窗的快捷鍵，也可設定物品「更多資訊」快捷鍵。",
        ["Allagan Tools can add extra information to the tooltips for items. Select which you would like to show in the tooltip. For further configuration including the ability to change each tooltips colour and settings specific to each tooltip please open the configuration window."] = "Allagan Tools 可在物品提示加入額外資訊。請選擇要顯示的內容；顏色與各模組詳細設定可在設定視窗調整。",
        ["How should the main items window and craft windows be laid out? Should we display your lists as tabs or in a side bar?"] = "選擇物品與製作視窗的版面，並決定清單使用分頁或側邊欄顯示。",
        ["Configure the marketboard integration. This downloads data from Universalis on a set timer, allowing you to filter against the minimum and average prices of items across multiple servers."] = "設定市場布告板整合。插件會定期從 Universalis 下載資料，讓你依多個世界的最低價與平均價篩選物品。",

        // Help text
        ["Should your character's home world be automatically priced?"] = "是否自動查詢角色所屬世界的市場價格？",
        ["Should the currently active world be automatically priced?"] = "是否自動查詢角色目前所在世界的市場價格？",
        ["A list of extra worlds we should automatically price"] = "選擇要額外自動查價的世界。",
        ["Should price data be automatically downloaded when it's viewed in a list?"] = "在清單顯示物品時，是否自動下載其市場價格？",
        ["How long should we store the market prices for before refreshing from universalis?"] = "從 Universalis 重新整理前，市場價格快取要保留多久？",
        ["How many minutes should there be between each auto save?"] = "每次自動儲存之間要間隔幾分鐘？",
        ["Set the layout of the craft window"] = "設定製作視窗的版面配置。",
        ["Set the layout of the items window"] = "設定物品視窗的版面配置。",
        ["What view is the craft list currently in?"] = "選擇製作清單目前的檢視方式。",
        ["The current state of the craft overlay window."] = "設定製作浮動視窗目前的展開狀態。",
        ["Should the craft overlay stay open between plugin reloads/game reloads?"] = "插件或遊戲重新載入後，是否保留製作浮動視窗的狀態？",
        ["When the craft overlay is expanded, how many items should be shown?"] = "製作浮動視窗展開時最多顯示多少項目？",
        ["Should the craft overlay be hidden during duties/cutscenes/chocobo racing/etc?"] = "進行任務、過場動畫、陸行鳥競賽等內容時，是否隱藏製作浮動視窗？",
        ["Should the name of the retainer in the summoning bell list be coloured if a relevant item is to be sorted or is available in their inventory?"] = "若雇員持有清單需要的物品，是否在傳喚鈴清單以顏色標示其名稱？",
        ["Should the name of the retainer in the summoning bell list have the number of items to be sorted or are available in their inventory?"] = "是否在傳喚鈴清單顯示各雇員持有或待整理的相關物品數量？",
        ["The color to set the retainer(when the retainer contains filtered items) list to."] = "雇員持有符合篩選物品時使用的清單標示顏色。",
        ["The color to set the highlighted items to."] = "設定符合條件物品的標示顏色。",
        ["The color to set the highlighted tabs(that contain filtered items) to."] = "設定含有符合條件物品之分頁的標示顏色。",
        ["The color to set any items in the destination that match your source filter(assuming highlight destination duplicates is on)."] = "設定目的地中與來源篩選相符物品的標示顏色。",
        ["When highlighting is turned on for a list, should it always be active or should it only be active when a column is being searched in"] = "清單啟用標示後，要永遠標示，還是僅在搜尋欄位時標示？",
        ["When highlighting destination items should the colour of the items be inverted?"] = "標示目的地物品時，是否反轉標示顏色？",
        ["When highlighting destinations should empty spots be highlighted or only items that already exist in the destination?"] = "標示目的地時，要連空格一起標示，還是只標示既有物品？",
        ["Should the destination for items be highlighted? This can be overridden in the filter configuration."] = "是否標示物品的目的地？每個篩選清單可個別覆寫此設定。",
        ["Should all the items not matching a list be highlighted instead? This can be overridden in the list configuration."] = "是否改為標示所有不符合清單的物品？每個清單可個別覆寫。",
        ["Should all the tabs not matching a list be highlighted instead? This can be overridden in the list configuration."] = "是否改為標示所有不含符合物品的分頁？每個清單可個別覆寫。",
        ["This is the craft list that crafts will count towards."] = "製作完成的數量會計入這個製作清單。",
        ["This is the list that is currently being highlighted when the allagan tools window is not visible. This list can be toggled with the associated slash commands."] = "Allagan Tools 視窗關閉時，使用此清單進行背景標示；也可用對應指令切換。",
        ["This is the list that will be highlighted when any of the allagan tools windows are visible."] = "任一 Allagan Tools 視窗開啟時，使用此清單進行標示。",
        ["When you view a different list, should highlighting automatically switch to the list you are viewing? Highlighting will only change to the new list if highlighting is already active."] = "查看其他清單時，是否自動把標示切換到該清單？只有目前已啟用標示時才會切換。",
        ["Should the active craft list automatically change when moving between each craft list? The active craft list will only change if there is an active craft list already selected."] = "切換製作清單時，是否自動更新目前製作清單？必須先已有一個啟用中的製作清單。",
        ["Should characters not currently logged in and their associated retainers be available to view/search and filter against? Each list can have it's sources/destinations configured to include/exclude retainers/free companies that are related to the currently logged in character."] = "是否允許檢視、搜尋及篩選其他角色與其雇員的庫存？各清單仍可設定要包含的角色、雇員及部隊。",
        ["Should the active background list be saved when exiting the game or disabling/re-enabling the plugin?"] = "離開遊戲或停用／重新啟用插件時，是否保留目前背景標示清單？",
        ["Should the main window show the tab called 'All Lists' containing all available lists in one tab?"] = "主視窗是否顯示「所有清單」分頁，集中顯示全部清單？",
        ["Should the inventories/configuration be automatically saved on a defined interval? While the plugin does save when the game is closed and when configurations are altered, it is not saved in cases of crashing so this attempts to alleviate this."] = "是否定期自動儲存庫存與設定？插件雖會在關閉或修改設定時儲存，但此功能可降低當機造成的資料遺失。",
        ["Should Allagan Tools attempt to track the movement, addition and removal of items in your inventories?"] = "是否記錄庫存物品的移動、增加與移除歷史？",
        ["Which events should be tracked by the history module?"] = "選擇歷史模組要記錄的事件種類。",
        ["Disable/enable the entire tooltip modification system for the plugin. If this is off, no changes will be made to your item's tooltips."] = "啟用或停用整個物品提示增強系統；關閉後不會修改任何物品提示。",
        ["Should [Allagan Tools] be displayed in the tooltip above any tooltip modifications?"] = "是否在新增的物品提示內容上方顯示 [Allagan Tools]？",
        ["When hovering an item, should the tooltip show the locations of any copies of the item you currently own?"] = "游標停在物品上時，是否顯示目前持有物品的位置？",
        ["The maximum amount of locations to list on the tooltip. This requires 'Display Amount Owned?' to be enabled."] = "物品提示最多列出多少個持有位置；必須先啟用「加入物品持有位置」。",
        ["When showing the locations of the items you own in the tooltip, which inventories should be included in the search?"] = "顯示持有位置時，要搜尋哪些庫存範圍？",
        ["How the locations of items should be presented in the tooltip. This requires 'Add Item Locations?' to be on."] = "選擇持有位置在物品提示中的顯示格式；必須先啟用「加入物品持有位置」。",
        ["How should the items displayed in the tooltip that you own be ordered? None is included if you find the sorting to be non-performant."] = "選擇持有物品位置的排序方式；若排序影響效能可選擇不排序。",
        ["When hovering an item and you have an amount owned by a retainer, should the owner of that retainer be affixed to that item?"] = "物品由雇員持有時，是否一併顯示該雇員所屬角色？",
        ["Limits the information displayed on the tooltip to inventories belonging to the currently logged in character."] = "只顯示目前登入角色及其關聯庫存的資訊。",
        ["When hovering an item, should the tooltip contain the average market price for both NQ and HQ. Please make sure 'Automatically download prices' is enabled."] = "是否在物品提示顯示 NQ／HQ 平均市場價格？請先啟用自動下載價格。",
        ["When hovering an item, should the tooltip contain the minimum market price for both NQ and HQ. Please make sure 'Automatically download prices' is enabled."] = "是否在物品提示顯示 NQ／HQ 最低市場價格？請先啟用自動下載價格。",
        ["Should the amount required to be retrieved be shown in the tooltip?"] = "是否在物品提示顯示需要從庫存取出的數量？",
        ["If an item can be unlocked/acquired, shows if your characters have unlocked/acquired said item. Can be configured to show specific characters inside the configuration window."] = "物品可解鎖或取得時，顯示各角色是否已解鎖；可在設定中指定角色。",
        ["When showing the unlock status on items, these characters will be displayed. Leave empty to display all characters."] = "選擇要顯示解鎖狀態的角色；留空表示全部角色。",
        ["How should the item unlock status tooltip be displayed?"] = "選擇物品解鎖狀態的顯示方式。",
        ["Should characters that already have this unlocked be hidden? If in grouped mode, this will hide the acquired group."] = "是否隱藏已解鎖此物品的角色？分組模式下會隱藏已取得群組。",
        ["Should source information be shown in the tooltip? For example that an item can be sourced via crafting, shops, monsters etc"] = "是否在物品提示顯示取得來源，例如製作、商店、怪物等？",
        ["Should use information be shown in the tooltip? For example, the item is used in a recipe or as currency at a shop, etc"] = "是否在物品提示顯示用途，例如配方素材或商店貨幣等？",
        ["Should the tooltip only be shown if a modifier key is pressed?"] = "是否僅在按住指定輔助鍵時顯示此段提示？",
        ["If the source information tooltip is enabled, how should the various sources be ordered/displayed/etc?"] = "設定取得來源資訊的排序、分組與顯示方式。",
        ["If the use information tooltip is enabled, how should the various uses be ordered/displayed/etc?"] = "設定用途資訊的排序、分組與顯示方式。",
        ["Displays the last patch an ingredient was used in. This is calculated by going each recipe an item is part of, then through it's recipes and so on until the highest patch is determined."] = "顯示此素材最後被配方使用的遊戲版本；會沿配方關係向上計算最高版本。",
        ["This is the colour of any text added to the item tooltip. You can give each tooltip module it's own colour by going into the tooltip's settings."] = "設定插件新增至物品提示的文字顏色；各提示模組也可分別指定顏色。",
        ["When source acquisition icons are displayed, how should they be grouped?"] = "顯示取得來源圖示時，要如何分組？",
        ["When use acquisition icons are displayed, how should they be grouped?"] = "顯示用途圖示時，要如何分組？",
        ["When searching for an item across the inventories AT knows about, which inventories should be searched?"] = "從 Allagan Tools 已知庫存搜尋物品時，要包含哪些庫存？",
        ["Performs a search covering either all inventories or the scope defined below?"] = "右鍵搜尋要涵蓋全部庫存，還是只搜尋下方指定範圍？",
        ["Add a submenu to add the item to a active craft list?"] = "是否加入可將物品新增至目前製作清單的子選單？",
        ["Add a submenu to add the item to a craft list?"] = "是否加入可將物品新增至任意製作清單的子選單？",
        ["Add a submenu to add the item to a curated list?"] = "是否加入可將物品新增至自訂清單的子選單？",
        ["Add a submenu to add/remove the item to/from your favourites?"] = "是否加入可將物品加入／移除最愛的子選單？",
        ["Add the more information item to the right click/context menu for items?"] = "是否在物品右鍵選單加入「更多資訊」？",
        ["Add a context menu item to open the crafting log for any item that can be crafted?"] = "是否在可製作物品的右鍵選單加入「開啟製作筆記」？",
        ["Add a context menu item to open the gathering log for any item that can be gathered?"] = "是否在可採集物品的右鍵選單加入「開啟採集筆記」？",
        ["Add a context menu item to open the fishing log for any item that can be fished?"] = "是否在可釣取物品的右鍵選單加入「開啟釣魚手冊」？",
        ["The hotkey to toggle the configuration window."] = "切換設定視窗的快捷鍵。",
        ["The hotkey to open the crafting log for an item when hovering it."] = "游標停在物品上時，開啟該物品製作筆記的快捷鍵。",
        ["The hotkey to open the gathering log for an item when hovering it."] = "游標停在物品上時，開啟該物品採集筆記的快捷鍵。",
        ["The hotkey to open the fishing log for an item when hovering it."] = "游標停在物品上時，開啟該物品釣魚手冊的快捷鍵。",
        ["The hotkey to open the more information window for an item when hovering it."] = "游標停在物品上時，開啟更多資訊視窗的快捷鍵。",
        ["The hotkey to open the relevant log entry(gathering, crafting, fishing) for an item when hovering it."] = "游標停在物品上時，開啟相關製作／採集／釣魚筆記的快捷鍵。",
        ["When enabled, what colour should the text be for the 'Add Item Locations' tooltip text be?"] = "啟用後，「物品持有位置」提示文字要使用什麼顏色？",
        ["When enabled, what colour should the text be for the 'Market Pricing' tooltip text be?"] = "啟用後，「市場價格」提示文字要使用什麼顏色？",
        ["When enabled, what colour should the text be for the 'Amount to Retrieve' tooltip text be?"] = "啟用後，「需取出數量」提示文字要使用什麼顏色？",
        ["When enabled, what colour should the text be for the 'Item Unlock Status' tooltip text be?"] = "啟用後，「物品解鎖狀態」提示文字要使用什麼顏色？",
        ["When enabled, what colour should the text be for the 'Source Information' tooltip text be?"] = "啟用後，「取得來源資訊」提示文字要使用什麼顏色？",
        ["When enabled, what colour should the text be for the 'Use Information' tooltip text be?"] = "啟用後，「用途資訊」提示文字要使用什麼顏色？",
        ["When enabled, what colour should the text be for the 'Ingredient Patch' tooltip text be?"] = "啟用後，「素材最後使用版本」提示文字要使用什麼顏色？",
        ["Use the old craft tracker, this only tracks crafts and uses a different mechanism to the new acquisition tracker."] = "使用舊版製作追蹤器；它只追蹤製作，運作方式與新版取得追蹤器不同。",
        ["When highlighting items in a shop, should the not highlighted items be disabled?"] = "商店標示啟用時，是否將未標示物品設為不可選？",
        ["Should a tooltip for items be shown, never, when hovering an item's icon or when hovering any row within an item table?"] = "選擇物品提示永不顯示、僅停在圖示時顯示，或停在整列任意位置時顯示。",
        ["Adds a button to the title menu along side the dalamud menu items allowing you to open Allagan Tools while not logged in."] = "在標題畫面的 Dalamud 選單旁加入按鈕，未登入角色時也能開啟 Allagan Tools。",
        ["Should tetris be enabled? If enabled a new 'Tetris' option will show up in the hamburger menus in the plugin."] = "是否啟用俄羅斯方塊？啟用後會在插件選單中出現「俄羅斯方塊」。",
        ["How many new lines should be added above any tooltip modifications made by this plugin?"] = "插件新增的物品提示內容上方要保留幾個空行？",
        ["How many new lines should be added below any tooltip modifications made by this plugin?"] = "插件新增的物品提示內容下方要保留幾個空行？",
        ["Makes the Tooltip Category Whitelist into a Blacklist if checked."] = "勾選後，提示分類白名單會改成黑名單模式。",
        ["When adding information to tooltips, should we limit the items affected to these categories? If 'Tooltip Category Blacklist` is checked, this functionality will be reversed."] = "只對選定分類的物品加入提示資訊；若啟用提示分類黑名單，效果會反轉。",
        ["When calculating the total number of sales for an item, this is how many days back should be examined for sales data to calculate that number. If you change this, the existing data will not be wiped, you will need to either manually request a refresh of MB prices OR wait for the marketboard refresh to happen automatically."] = "計算物品成交數量時，要回溯多少天的成交資料。變更後不會清除既有資料，請手動重新整理市場價格或等待自動更新。",
        ["The acquisition tracker perform an initial scan of your characters bags when you login. As the game receives multiple inventory updates, the scanner must wait a set amount of time before it's done. Adjust this to be higher if you are seeing items in your craft list randomly complete when you first login."] = "登入後，取得追蹤器會先掃描角色背包。遊戲會分批傳入庫存更新，因此需等待一段時間；若剛登入時製作清單會誤判完成，可提高此數值。",
        ["The acquisition tracker will track your current state(crafting, gathering, etc). It will keep this state by default for 2 seconds after it changes back to doing nothing. This is to catch any delays in the tracker, set this number higher if you find the tracker is not picking up items you craft/gather/etc"] = "取得追蹤器會記錄目前是製作、採集等狀態，恢復閒置後仍保留數秒以涵蓋延遲；若漏記取得的物品，可提高此數值。",
        ["Should the plugin track where mobs spawn as you move around. This data is not used by the plugin yet but once you have collected enough you can hit the button next to the checkbox to export a file containing those positions. If you upload those CSVs and send a url to via feedback I can use that spawn data to provide accurate mob spawns for everyone."] = "移動時記錄怪物出現位置。此資料目前不會直接影響插件；累積後可用旁邊按鈕匯出 CSV，供上游改善怪物位置資料。",
        ["The hotkey to toggle the airships window."] = "切換飛空艇視窗的快捷鍵。",
        ["The hotkey to toggle the craft window."] = "切換製作視窗的快捷鍵。",
        ["The hotkey to toggle the duties window."] = "切換任務視窗的快捷鍵。",
        ["The hotkey to toggle the lists window."] = "切換物品清單視窗的快捷鍵。",
        ["The hotkey to toggle the mob window."] = "切換怪物視窗的快捷鍵。",
        ["The hotkey to toggle the retainer ventures window."] = "切換雇員探險視窗的快捷鍵。",
        ["The hotkey to toggle the submarines window."] = "切換潛水艇視窗的快捷鍵。",

        // Common choices and controls
        ["Reset"] = "重設",
        ["Enable"] = "啟用",
        ["None"] = "無",
        ["No Order"] = "不排序",
        ["Always"] = "永遠",
        ["Never"] = "永不",
        ["When Searching"] = "搜尋時",
        ["Grouped"] = "分組",
        ["Ungrouped"] = "不分組",
        ["Default"] = "預設",
        ["Character Per Line"] = "每個角色一行",
        ["Grouped By Unlock Status"] = "依解鎖狀態分組",
        ["Collapsed"] = "收合",
        ["Expanded"] = "展開",
        ["Single"] = "單項",
        ["List"] = "清單",
        ["Treeview"] = "樹狀檢視",
        ["Crafts"] = "製作項目",
        ["Configuration"] = "設定",
        ["Sidebar"] = "側邊欄",
        ["Tabs"] = "分頁",
        ["Icon"] = "圖示",
        ["Icons"] = "僅物品圖示",
        ["Row"] = "整列",
        ["Everywhere"] = "整列任意位置",
        ["Control"] = "Ctrl",
        ["Shift"] = "Shift",
        ["Alphabetical Order(Character/Retainer/etc)"] = "依角色／雇員名稱排序",
        ["Alphabetical Order(Category)"] = "依庫存分類排序",
        ["Item Quantity"] = "依物品數量排序",
        ["Character/Retainer - Quantity - Quality"] = "角色／雇員－數量－品質",
        ["Character/Retainer - Bag - Slot - Quality"] = "角色／雇員－背包－格位－品質",
        ["Character/Retainer - Bag - Slot - Quantity"] = "角色／雇員－背包－格位－數量",
        ["Character/Retainer - Category - Quantity - Quality"] = "角色／雇員－分類－數量－品質",
        ["Left"] = "左側",
        ["Right"] = "右側",
        ["Top"] = "上方",
        ["Bottom"] = "下方",
        ["Always show"] = "永遠顯示",
        ["Hide during duties"] = "任務中隱藏",
        ["All characters will be shown."] = "將顯示所有角色。",
    };

    public static string Translate(string? value)
    {
        if (string.IsNullOrEmpty(value))
            return value ?? string.Empty;

        return Text.TryGetValue(value, out var translated) ? translated : value;
    }

    public static void Apply(IEnumerable<ISetting> settings)
    {
        foreach (var setting in settings)
        {
            setting.Name = Translate(setting.Name);
            setting.HelpText = Translate(setting.HelpText);
        }
    }
}
